# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



from openapi_client.models.order_status import OrderStatus  # noqa: E501

class TestOrderStatus:
    """OrderStatus unit test stubs"""

    def setup_method(self):
        pass

    def teardown_method(self):
        pass

    def testOrderStatus(self):
        """Test OrderStatus"""
        # inst = OrderStatus()
