# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



from openapi_client.models.location_inner import LocationInner  # noqa: E501

class TestLocationInner:
    """LocationInner unit test stubs"""

    def setup_method(self):
        pass

    def teardown_method(self):
        pass

    def make_instance(self, include_optional) -> LocationInner:
        """Test LocationInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocationInner`
        """
        model = LocationInner()  # noqa: E501
        if include_optional:
            return LocationInner(
            )
        else:
            return LocationInner(
        )
        """

    def testLocationInner(self):
        """Test LocationInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)
