# coding: utf-8

"""
Petstore API

A production-ready Petstore API built with FastAPI.

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import pytest
import pytest_asyncio

from petstore_openapi_client.api.health_api import HealthApi
from petstore_openapi_client.models.health_response import HealthResponse
from petstore_openapi_client import ApiClient
from petstore_openapi_client.assertions import assert_that


@pytest_asyncio.fixture()
async def health_api_client(api_client: ApiClient):
    api = HealthApi(api_client=api_client)
    yield api


@pytest.mark.asyncio
class TestHealthApi:
    """HealthApi unit test stubs"""

    async def test_health_check_health_get(self, health_api_client: HealthApi) -> None:
        """Test case for health_check_health_get

        Health Check
        """
        response = await health_api_client.health_check_health_get()

        assert_that(response).is_not_none().is_instance_of(HealthResponse)
        assert_that(response.status).equals("ok")
        assert response is not None
        if isinstance(response, dict):
            assert "status" in response
