# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.location_inner import LocationInner
from openapi_client.models.validation_error import ValidationError

class TestHTTPValidationError:
    """HTTPValidationError model tests."""

    def test_http_validation_error_allows_empty_instance(self) -> None:
        http_error = HTTPValidationError()

        assert http_error.detail is None

    def test_http_validation_error_with_detail(self) -> None:
        detail_item = ValidationError(
            loc=[LocationInner("body"), LocationInner("name")],
            msg="field required",
            type="missing",
        )
        http_error = HTTPValidationError(detail=[detail_item])

        assert http_error.detail is not None
        assert len(http_error.detail) == 1
        assert http_error.detail[0].msg == "field required"
