# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest

from openapi_client.models.user_update import UserUpdate

class TestUserUpdate:
    """UserUpdate unit test stubs"""

    def make_instance(self, include_optional: bool) -> UserUpdate:
        """Create an UserUpdate instance for testing.

        Args:
            include_optional (bool):
                If False, only the required parameters should be included.
                If True, both required and optional parameters should be included.

        Returns:
            UserUpdate: A populated UserUpdate model instance.

        TODO:
            Replace the placeholder example values below with meaningful test data
            appropriate for your API. These are only illustrative defaults.

        Example:
            if include_optional:
                return UserUpdate(
                    username = '',
                    first_name = '',
                    last_name = '',
                    email = '',
                    phone = '',
                    user_status = 56,
                    password = ''
                )
            else:
                return UserUpdate(
            )
        """
        raise NotImplementedError("Populate example values before using this helper.")

    @pytest.mark.skip(reason="Generated stub test - implement assertions")
    def testUserUpdate(self):
        """Test UserUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)
