# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.order_status import OrderStatus  # noqa: E501

class TestOrderStatus(unittest.TestCase):
    """OrderStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderStatus(self):
        """Test OrderStatus"""
        # inst = OrderStatus()

if __name__ == '__main__':
    unittest.main()
