# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from petstore_openapi_client.models.tag import Tag

class TestTag:
    """Tag model tests."""

    def test_tag_optional_fields(self) -> None:
        tag = Tag(id=2, name="friendly")

        assert tag.id == 2
        assert tag.name == "friendly"

    def test_tag_allows_empty_instance(self) -> None:
        tag = Tag()

        assert tag.id is None
        assert tag.name is None

    def test_tag_serialization_round_trip(self) -> None:
        tag = Tag(id=4, name="active")

        as_dict = tag.to_dict()
        assert as_dict == {"id": 4, "name": "active"}

        from_dict = Tag.from_dict(as_dict)
        assert from_dict == tag

        as_json = tag.to_json()
        from_json = Tag.from_json(as_json)
        assert from_json == tag

        assert "active" in tag.to_str()
