# coding: utf-8

"""
Petstore API

A production-ready Petstore API built with FastAPI.

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import pytest

from petstore_openapi_client.models.health_details import HealthDetails
from petstore_openapi_client.models.health_response import HealthResponse


class TestHealthResponse:
    """HealthResponse model tests."""

    def test_health_response_accepts_valid_status(self) -> None:
        response = HealthResponse(
            status="ok",
            mode="standalone",
            details=HealthDetails(
                version="1.0.0",
                build_date="2026-05-15T12:00:00Z",
                git_commit_sha="cafebabe",
            ),
        )

        assert response.status == "ok"
        assert response.mode == "standalone"
        assert response.details.version == "1.0.0"

    def test_health_response_rejects_invalid_status(self) -> None:
        with pytest.raises(ValueError, match="must be one of enum values"):
            HealthResponse(
                status="down",
                mode="standalone",
                details=HealthDetails(
                    version="1.0.0",
                    build_date="2026-05-15T12:00:00Z",
                    git_commit_sha="cafebabe",
                ),
            )

    def test_health_response_serialization_round_trip(self) -> None:
        response = HealthResponse(
            status="ok",
            mode="readonly",
            details=HealthDetails(
                version="2.1.0",
                build_date="2026-05-10T08:30:00Z",
                git_commit_sha="facefeed",
            ),
        )

        as_dict = response.to_dict()
        assert as_dict == {
            "status": "ok",
            "mode": "readonly",
            "details": {
                "version": "2.1.0",
                "build_date": "2026-05-10T08:30:00Z",
                "git_commit_sha": "facefeed",
            },
        }

        from_dict = HealthResponse.from_dict(as_dict)
        assert from_dict == response

        as_json = response.to_json()
        from_json = HealthResponse.from_json(as_json)
        assert from_json == response

        assert "readonly" in response.to_str()

    def test_health_response_from_dict_none_returns_none(self) -> None:
        assert HealthResponse.from_dict(None) is None
