# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest

from openapi_client.models.location_inner import LocationInner
from openapi_client.models.validation_error import ValidationError

class TestValidationError:
    """ValidationError model tests."""

    def test_validation_error_requires_loc_msg_type(self) -> None:
        with pytest.raises(ValueError):
            ValidationError()

    def test_validation_error_with_required_only(self) -> None:
        error = ValidationError(
            loc=[LocationInner("body"), LocationInner("field")],
            msg="field required",
            type="missing",
        )

        assert len(error.loc) == 2
        assert error.msg == "field required"
        assert error.type == "missing"

    def test_validation_error_with_optional_fields(self) -> None:
        error = ValidationError(
            loc=[LocationInner("query"), LocationInner("limit")],
            msg="invalid",
            type="value_error",
            input="abc",
            ctx={"limit": 10},
        )

        assert error.input == "abc"
        assert error.ctx == {"limit": 10}
