# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest

from openapi_client.models.order_create import OrderCreate

class TestOrderCreate:
    """OrderCreate unit test stubs"""

    def make_instance(self, include_optional: bool) -> OrderCreate:
        """Create an OrderCreate instance for testing.

        Args:
            include_optional (bool):
                If False, only the required parameters should be included.
                If True, both required and optional parameters should be included.

        Returns:
            OrderCreate: A populated OrderCreate model instance.

        TODO:
            Replace the placeholder example values below with meaningful test data
            appropriate for your API. These are only illustrative defaults.

        Example:
            if include_optional:
                return OrderCreate(
                    pet_id = 56,
                    quantity = 56,
                    ship_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                    status = 'placed',
                    complete = True
                )
            else:
                return OrderCreate(
            )
        """
        raise NotImplementedError("Populate example values before using this helper.")

    @pytest.mark.skip(reason="Generated stub test - implement assertions")
    def testOrderCreate(self):
        """Test OrderCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)
