# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.pet_create import PetCreate  # noqa: E501

class TestPetCreate(unittest.TestCase):
    """PetCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PetCreate:
        """Test PetCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PetCreate`
        """
        model = PetCreate()  # noqa: E501
        if include_optional:
            return PetCreate(
                name = '0',
                photo_urls = [
                    ''
                    ],
                category = openapi_client.models.category.Category(
                    id = 56, 
                    name = '', ),
                tags = [
                    openapi_client.models.tag.Tag(
                        id = 56, 
                        name = '', )
                    ],
                status = 'available'
            )
        else:
            return PetCreate(
                name = '0',
        )
        """

    def testPetCreate(self):
        """Test PetCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
