# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.pet_update import PetUpdate  # noqa: E501

class TestPetUpdate(unittest.TestCase):
    """PetUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PetUpdate:
        """Test PetUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PetUpdate`
        """
        model = PetUpdate()  # noqa: E501
        if include_optional:
            return PetUpdate(
                name = '0',
                photo_urls = [
                    ''
                    ],
                category = openapi_client.models.category.Category(
                    id = 56, 
                    name = '', ),
                tags = [
                    openapi_client.models.tag.Tag(
                        id = 56, 
                        name = '', )
                    ],
                status = 'available',
                id = 56
            )
        else:
            return PetUpdate(
                name = '0',
                id = 56,
        )
        """

    def testPetUpdate(self):
        """Test PetUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
