# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from petstore_openapi_client.models.location_inner import LocationInner

class TestLocationInner:
    """LocationInner model tests."""

    def test_location_inner_with_string(self) -> None:
        location = LocationInner("body")

        assert location.actual_instance == "body"

    def test_location_inner_with_int(self) -> None:
        location = LocationInner(5)

        assert location.actual_instance == 5

    def test_location_inner_serialization_round_trip(self) -> None:
        location = LocationInner("body")

        as_json = location.to_json()
        from_json = LocationInner.from_json(as_json)
        assert from_json.actual_instance == "body"

        as_dict = location.to_dict()
        assert as_dict == "body"

        assert "body" in location.to_str()
