# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest

from openapi_client.models.category import Category
from openapi_client.models.pet_create import PetCreate
from openapi_client.models.pet_status import PetStatus
from openapi_client.models.tag import Tag

class TestPetCreate:
    """PetCreate model tests."""

    def test_pet_create_requires_name(self) -> None:
        with pytest.raises(ValueError):
            PetCreate()

    def test_pet_create_with_required_only(self) -> None:
        pet = PetCreate(name="pet-required")

        assert pet.name == "pet-required"
        assert pet.status is None

    def test_pet_create_with_optional_fields(self) -> None:
        pet = PetCreate(
            name="pet-optional",
            photo_urls=["https://example.com/photo.png"],
            category=Category(id=1, name="dogs"),
            tags=[Tag(id=1, name="small")],
            status=PetStatus.AVAILABLE,
        )

        assert pet.photo_urls == ["https://example.com/photo.png"]
        assert pet.category is not None
        assert pet.category.name == "dogs"
        assert pet.tags is not None
        assert pet.tags[0].name == "small"
        assert pet.status == PetStatus.AVAILABLE
