# coding: utf-8

"""
Petstore API

A production-ready Petstore API built with FastAPI.

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

from petstore_openapi_client.models.health_details import HealthDetails


class TestHealthDetails:
    """HealthDetails model tests."""

    def test_health_details_required_fields(self) -> None:
        details = HealthDetails(
            version="1.2.3",
            build_date="2026-05-15T12:00:00Z",
            git_commit_sha="abc123def456",
        )

        assert details.version == "1.2.3"
        assert details.build_date == "2026-05-15T12:00:00Z"
        assert details.git_commit_sha == "abc123def456"

    def test_health_details_serialization_round_trip(self) -> None:
        details = HealthDetails(
            version="2.0.0",
            build_date="2026-05-10T08:30:00Z",
            git_commit_sha="deadbeef",
        )

        as_dict = details.to_dict()
        assert as_dict == {
            "version": "2.0.0",
            "build_date": "2026-05-10T08:30:00Z",
            "git_commit_sha": "deadbeef",
        }

        from_dict = HealthDetails.from_dict(as_dict)
        assert from_dict == details

        as_json = details.to_json()
        from_json = HealthDetails.from_json(as_json)
        assert from_json == details

        assert "2.0.0" in details.to_str()

    def test_health_details_from_dict_none_returns_none(self) -> None:
        assert HealthDetails.from_dict(None) is None
