# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from openapi_client.models.user import User

class TestUser:
    """User model tests."""

    def test_user_allows_empty_instance(self) -> None:
        user = User()

        assert user.username is None
        assert user.id is None

    def test_user_with_optional_fields(self) -> None:
        user = User(
            username="jdoe",
            first_name="John",
            last_name="Doe",
            email="jdoe@example.com",
            phone="555-1000",
            user_status=1,
            id=9,
        )

        assert user.username == "jdoe"
        assert user.first_name == "John"
        assert user.last_name == "Doe"
        assert user.email == "jdoe@example.com"
        assert user.phone == "555-1000"
        assert user.user_status == 1
        assert user.id == 9

    def test_user_serialization_round_trip(self) -> None:
        user = User(
            username="jdoe",
            first_name="John",
            last_name="Doe",
            email="jdoe@example.com",
            phone="555-1000",
            user_status=1,
            id=9,
        )

        as_dict = user.to_dict()
        assert as_dict["username"] == "jdoe"
        assert as_dict["id"] == 9

        from_dict = User.from_dict(as_dict)
        assert from_dict.username == user.username
        assert from_dict.id == user.id

        as_json = user.to_json()
        from_json = User.from_json(as_json)
        assert from_json.username == user.username
        assert from_json.id == user.id

        assert "jdoe" in user.to_str()
