# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from datetime import datetime

from openapi_client.models.order_create import OrderCreate
from openapi_client.models.order_status import OrderStatus

class TestOrderCreate:
    """OrderCreate model tests."""

    def test_order_create_allows_empty_instance(self) -> None:
        order_create = OrderCreate()

        assert order_create.pet_id is None
        assert order_create.quantity is None

    def test_order_create_with_optional_fields(self) -> None:
        ship_date = datetime(2024, 1, 2, 3, 4, 5)
        order_create = OrderCreate(
            pet_id=20,
            quantity=5,
            ship_date=ship_date,
            status=OrderStatus.APPROVED,
            complete=False,
        )

        assert order_create.pet_id == 20
        assert order_create.quantity == 5
        assert order_create.ship_date == ship_date
        assert order_create.status == OrderStatus.APPROVED
        assert order_create.complete is False
