# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from openapi_client.models.user_update import UserUpdate

class TestUserUpdate:
    """UserUpdate model tests."""

    def test_user_update_allows_empty_instance(self) -> None:
        user_update = UserUpdate()

        assert user_update.username is None
        assert user_update.password is None

    def test_user_update_with_optional_fields(self) -> None:
        user_update = UserUpdate(
            username="updated-user",
            first_name="Updated",
            last_name="User",
            email="updated@example.com",
            phone="555-3000",
            user_status=3,
            password="new-secret",
        )

        assert user_update.username == "updated-user"
        assert user_update.first_name == "Updated"
        assert user_update.last_name == "User"
        assert user_update.email == "updated@example.com"
        assert user_update.phone == "555-3000"
        assert user_update.user_status == 3
        assert user_update.password == "new-secret"
