# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from openapi_client.models.category import Category

class TestCategory:
    """Category model tests."""

    def test_category_optional_fields(self) -> None:
        category = Category(id=1, name="dogs")

        assert category.id == 1
        assert category.name == "dogs"

    def test_category_allows_empty_instance(self) -> None:
        category = Category()

        assert category.id is None
        assert category.name is None

    def test_category_serialization_round_trip(self) -> None:
        category = Category(id=3, name="cats")

        as_dict = category.to_dict()
        assert as_dict == {"id": 3, "name": "cats"}

        from_dict = Category.from_dict(as_dict)
        assert from_dict == category

        as_json = category.to_json()
        from_json = Category.from_json(as_json)
        assert from_json == category

        assert "cats" in category.to_str()
