# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



from openapi_client.models.pet import Pet  # noqa: E501

class TestPet:
    """Pet unit test stubs"""

    def setup_method(self):
        pass

    def teardown_method(self):
        pass

    def make_instance(self, include_optional) -> Pet:
        """Test Pet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Pet`
        """
        model = Pet()  # noqa: E501
        if include_optional:
            return Pet(
                name = '0',
                photo_urls = [
                    ''
                    ],
                category = openapi_client.models.category.Category(
                    id = 56, 
                    name = '', ),
                tags = [
                    openapi_client.models.tag.Tag(
                        id = 56, 
                        name = '', )
                    ],
                status = 'available',
                id = 56
            )
        else:
            return Pet(
                name = '0',
        )
        """

    def testPet(self):
        """Test Pet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)
