# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from datetime import datetime

import pytest

from petstore_openapi_client.models.order import Order
from petstore_openapi_client.models.order_status import OrderStatus

class TestOrder:
    """Order model tests."""

    def test_order_allows_empty_instance(self) -> None:
        order = Order()

        assert order.id is None
        assert order.status is None

    def test_order_with_optional_fields(self) -> None:
        ship_date = datetime(2024, 1, 2, 3, 4, 5)
        order = Order(
            pet_id=10,
            quantity=2,
            ship_date=ship_date,
            status=OrderStatus.PLACED,
            complete=True,
            id=100,
        )

        assert order.pet_id == 10
        assert order.quantity == 2
        assert order.ship_date == ship_date
        assert order.status == OrderStatus.PLACED
        assert order.complete is True
        assert order.id == 100

    def test_order_serialization_round_trip(self) -> None:
        ship_date = datetime(2024, 1, 2, 3, 4, 5)
        order = Order(
            pet_id=10,
            quantity=2,
            ship_date=ship_date,
            status=OrderStatus.PLACED,
            complete=True,
            id=100,
        )

        as_dict = order.to_dict()
        assert as_dict["id"] == 100
        assert as_dict["status"] == "placed"

        from_dict = Order.from_dict(as_dict)
        assert from_dict.id == order.id
        assert from_dict.status == order.status

        # Generated model currently does not JSON-encode datetime in to_json.
        with pytest.raises(TypeError):
            order.to_json()

        json_payload = (
            '{"pet_id": 10, "quantity": 2, "ship_date": "2024-01-02T03:04:05", '
            '"status": "placed", "complete": true, "id": 100}'
        )
        from_json = Order.from_json(json_payload)
        assert from_json.id == order.id
        assert from_json.status == order.status

        assert "placed" in order.to_str()
