# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest

from petstore_openapi_client.models.category import Category
from petstore_openapi_client.models.pet import Pet
from petstore_openapi_client.models.pet_status import PetStatus
from petstore_openapi_client.models.tag import Tag

class TestPet:
    """Pet model tests."""

    def test_pet_requires_name(self) -> None:
        with pytest.raises(ValueError):
            Pet()

    def test_pet_with_required_only(self) -> None:
        pet = Pet(name="pet-required")

        assert pet.name == "pet-required"
        assert pet.id is None

    def test_pet_with_optional_fields(self) -> None:
        pet = Pet(
            id=7,
            name="pet-optional",
            photo_urls=["https://example.com/pet.png"],
            category=Category(id=1, name="birds"),
            tags=[Tag(id=1, name="flying")],
            status=PetStatus.SOLD,
        )

        assert pet.id == 7
        assert pet.photo_urls == ["https://example.com/pet.png"]
        assert pet.category is not None
        assert pet.category.name == "birds"
        assert pet.tags is not None
        assert pet.tags[0].name == "flying"
        assert pet.status == PetStatus.SOLD

    def test_pet_serialization_round_trip(self) -> None:
        pet = Pet(
            id=8,
            name="pet-serialize",
            photo_urls=["https://example.com/pet.png"],
            category=Category(id=1, name="birds"),
            tags=[Tag(id=1, name="flying")],
            status=PetStatus.SOLD,
        )

        as_dict = pet.to_dict()
        assert as_dict["id"] == 8
        assert as_dict["name"] == "pet-serialize"
        assert as_dict["status"] == "sold"

        from_dict = Pet.from_dict(as_dict)
        assert from_dict.id == pet.id
        assert from_dict.name == pet.name
        assert from_dict.status == pet.status

        as_json = pet.to_json()
        from_json = Pet.from_json(as_json)
        assert from_json.id == pet.id
        assert from_json.status == pet.status

        assert "pet-serialize" in pet.to_str()
