# coding: utf-8

"""
Petstore API

A production-ready Petstore API built with FastAPI.

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from petstore_openapi_client.models.pet_status import PetStatus


class TestPetStatus:
    """PetStatus enum tests."""

    def test_pet_status_values(self) -> None:
        assert PetStatus.AVAILABLE.value == "available"
        assert PetStatus.PENDING.value == "pending"
        assert PetStatus.SOLD.value == "sold"

    def test_pet_status_from_value(self) -> None:
        assert PetStatus("available") == PetStatus.AVAILABLE
