# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest
import pytest_asyncio

from openapi_client.api.health_api import HealthApi  # noqa: E501
from openapi_client import ApiClient


@pytest_asyncio.fixture()
async def health_api_client(api_client: ApiClient):
    api = HealthApi(api_client=api_client)
    yield api


@pytest.mark.asyncio
class TestHealthApi:
    """HealthApi unit test stubs"""

    @pytest.mark.skip(reason="Generated stub test - implement assertions")
    async def test_health_check_health_get(self, health_api_client: HealthApi) -> None:
        """Test case for health_check_health_get

        Health Check  # noqa: E501
        """

