# coding: utf-8

"""
Petstore API

A production-ready Petstore API built with FastAPI.

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import pytest
import pytest_asyncio
from petstore_openapi_client.exceptions import ApiException

from petstore_openapi_client.api.user_api import UserApi  # noqa: E501
from petstore_openapi_client import ApiClient
from petstore_openapi_client.models.user import User
from petstore_openapi_client.models.user_create import UserCreate
from petstore_openapi_client.models.user_update import UserUpdate


@pytest_asyncio.fixture()
async def user_api_client(api_client: ApiClient):
    api = UserApi(api_client=api_client)
    yield api


@pytest.mark.asyncio
class TestUserApi:
    """UserApi unit test stubs"""

    @staticmethod
    def _build_user_create(username: str) -> UserCreate:
        return UserCreate(
            username=username,
            first_name="Integration",
            last_name="User",
            email=f"{username}@example.com",
            phone="555-0101",
            user_status=1,
            password="integration-password",
        )

    async def test_create_user(self, user_api_client: UserApi) -> None:
        """Test case for create_user

        Create User  # noqa: E501
        """
        created_user = await user_api_client.create_user(
            self._build_user_create(username="integration-create-user")
        )

        assert isinstance(created_user, User)
        assert created_user.id is not None
        assert created_user.username == "integration-create-user"

    async def test_create_users_with_list(self, user_api_client: UserApi) -> None:
        """Test case for create_users_with_list

        Create Users With List  # noqa: E501
        """
        users = await user_api_client.create_users_with_list(
            [
                self._build_user_create(username="integration-list-user-1"),
                self._build_user_create(username="integration-list-user-2"),
            ]
        )

        assert isinstance(users, list)
        assert len(users) == 2
        usernames = {user.username for user in users}
        assert "integration-list-user-1" in usernames
        assert "integration-list-user-2" in usernames

    async def test_delete_user(self, user_api_client: UserApi) -> None:
        """Test case for delete_user

        Delete User  # noqa: E501
        """
        username = "integration-delete-user"
        await user_api_client.create_user(self._build_user_create(username=username))

        delete_result = await user_api_client.delete_user(username)

        assert isinstance(delete_result, dict)
        assert delete_result

        with pytest.raises(ApiException) as exc_info:
            await user_api_client.get_user_by_name(username)
        assert exc_info.value.status == 404

    async def test_get_user_by_name(self, user_api_client: UserApi) -> None:
        """Test case for get_user_by_name

        Get User By Name  # noqa: E501
        """
        username = "integration-get-user"
        await user_api_client.create_user(self._build_user_create(username=username))

        fetched_user = await user_api_client.get_user_by_name(username)

        assert isinstance(fetched_user, User)
        assert fetched_user.username == username

    async def test_login_user(self, user_api_client: UserApi) -> None:
        """Test case for login_user

        Login User  # noqa: E501
        """
        username = "integration-login-user"
        password = "integration-password"
        await user_api_client.create_user(self._build_user_create(username=username))

        login_result = await user_api_client.login_user(
            username=username,
            password=password,
        )

        assert isinstance(login_result, dict)
        assert login_result

    async def test_logout_user(self, user_api_client: UserApi) -> None:
        """Test case for logout_user

        Logout User  # noqa: E501
        """
        logout_result = await user_api_client.logout_user()

        assert isinstance(logout_result, dict)
        assert logout_result

    async def test_update_user(self, user_api_client: UserApi) -> None:
        """Test case for update_user

        Update User  # noqa: E501
        """
        username = "integration-update-user"
        await user_api_client.create_user(self._build_user_create(username=username))

        updated_user = await user_api_client.update_user(
            username=username,
            user_update=UserUpdate(
                username=username,
                first_name="Updated",
                last_name="User",
                email=f"{username}@example.com",
                phone="555-0102",
                user_status=2,
                password="integration-password",
            ),
        )

        assert isinstance(updated_user, User)
        assert updated_user.username == username
        assert updated_user.first_name == "Updated"
