# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest

from petstore_openapi_client.models.location_inner import LocationInner
from petstore_openapi_client.models.validation_error import ValidationError

class TestValidationError:
    """ValidationError model tests."""

    def test_validation_error_requires_loc_msg_type(self) -> None:
        with pytest.raises(ValueError):
            ValidationError()

    def test_validation_error_with_required_only(self) -> None:
        error = ValidationError(
            loc=[LocationInner("body"), LocationInner("field")],
            msg="field required",
            type="missing",
        )

        assert len(error.loc) == 2
        assert error.msg == "field required"
        assert error.type == "missing"

    def test_validation_error_with_optional_fields(self) -> None:
        error = ValidationError(
            loc=[LocationInner("query"), LocationInner("limit")],
            msg="invalid",
            type="value_error",
            input="abc",
            ctx={"limit": 10},
        )

        assert error.input == "abc"
        assert error.ctx == {"limit": 10}

    def test_validation_error_serialization_round_trip(self) -> None:
        error = ValidationError(
            loc=[LocationInner("body"), LocationInner("field")],
            msg="field required",
            type="missing",
            input=None,
            ctx={"source": "test"},
        )

        as_dict = error.to_dict()
        assert as_dict["msg"] == "field required"
        assert as_dict["type"] == "missing"
        assert as_dict["loc"] == ["body", "field"]

        from_dict = ValidationError.from_dict(as_dict)
        assert from_dict.msg == error.msg
        assert from_dict.type == error.type

        as_json = error.to_json()
        from_json = ValidationError.from_json(as_json)
        assert from_json.msg == error.msg
        assert from_json.type == error.type

        assert "field required" in error.to_str()
