# coding: utf-8

"""
Petstore API

A production-ready Petstore API built with FastAPI.

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from petstore_openapi_client.assertions import assert_that

import pytest
import pytest_asyncio
from petstore_openapi_client.exceptions import ApiException

from petstore_openapi_client.api.pet_api import PetApi  # noqa: E501
from petstore_openapi_client import ApiClient
from petstore_openapi_client.models.pet import Pet
from petstore_openapi_client.models.pet_create import PetCreate
from petstore_openapi_client.models.pet_status import PetStatus
from petstore_openapi_client.models.pet_update import PetUpdate
from petstore_openapi_client.models.tag import Tag


@pytest_asyncio.fixture()
async def pet_api_client(api_client: ApiClient):
    api = PetApi(api_client=api_client)
    yield api


@pytest.mark.asyncio
class TestPetApi:
    """PetApi unit test stubs"""

    @staticmethod
    def _build_pet_create(
        name: str,
        tag_name: str | None = None,
        status: PetStatus = PetStatus.AVAILABLE,
    ) -> PetCreate:
        tags = [Tag(name=tag_name)] if tag_name else None
        return PetCreate(
            name=name,
            photoUrls=["https://example.com/pet.png"],
            status=status,
            tags=tags,
        )

    async def test_add_pet(self, pet_api_client: PetApi) -> None:
        """Test case for add_pet

        Add Pet  # noqa: E501
        """
        created_pet: Pet = await pet_api_client.add_pet(
            self._build_pet_create(name="integration-add-pet")
        )

        assert_that(created_pet).is_not_none().is_instance_of(Pet)
        assert_that(created_pet.id).is_not_none()
        assert_that(created_pet.name).equals("integration-add-pet")
        assert_that(created_pet.status).equals(PetStatus.AVAILABLE)

    async def test_delete_pet(self, pet_api_client: PetApi) -> None:
        """Test case for delete_pet

        Delete Pet  # noqa: E501
        """
        created_pet = await pet_api_client.add_pet(
            self._build_pet_create(name="integration-delete-pet")
        )
        assert created_pet.id is not None

        delete_result = await pet_api_client.delete_pet(created_pet.id)

        assert isinstance(delete_result, dict)
        assert delete_result

        with pytest.raises(ApiException) as exc_info:
            await pet_api_client.get_pet_by_id(created_pet.id)
        assert exc_info.value.status == 404

    async def test_find_pets_by_status(self, pet_api_client: PetApi) -> None:
        """Test case for find_pets_by_status

        Find Pets By Status  # noqa: E501
        """
        # Create one pet per supported status value
        pet_by_status: dict[PetStatus, Pet] = {}
        for status in PetStatus:
            pet = await pet_api_client.add_pet(
                self._build_pet_create(
                    name=f"integration-status-{status.value}-pet",
                    status=status,
                )
            )
            pet_by_status[status] = pet

        # For each valid status, verify that:
        #   - the pet created with that status appears in the results
        #   - the pets created with every other status do NOT appear
        for status in PetStatus:
            pets = await pet_api_client.find_pets_by_status(status=status)
            assert isinstance(pets, list)
            returned_ids = {pet.id for pet in pets if pet.id is not None}
            assert pet_by_status[status].id in returned_ids, (
                f"Expected pet with status={status.value} to be in results"
            )
            for other_status, other_pet in pet_by_status.items():
                if other_status != status:
                    assert other_pet.id not in returned_ids, (
                        f"Pet with status={other_status.value} should not appear "
                        f"when filtering by status={status.value}"
                    )

    async def test_find_pets_by_status_invalid_value_returns_422(
        self, pet_api_client: PetApi
    ) -> None:
        """The API must reject an unrecognised status value with 422."""
        with pytest.raises(ApiException) as exc_info:
            await pet_api_client.find_pets_by_status_without_validation(status="foobar")
        assert exc_info.value.status == 422

    async def test_find_pets_by_tags(self, pet_api_client: PetApi) -> None:
        """Test case for find_pets_by_tags

        Find Pets By Tags  # noqa: E501
        """
        tag_name = "integration-tag"
        created_pet = await pet_api_client.add_pet(
            self._build_pet_create(name="integration-tag-pet", tag_name=tag_name)
        )

        pets = await pet_api_client.find_pets_by_tags(tags=[tag_name])

        assert isinstance(pets, list)
        assert any(pet.id == created_pet.id for pet in pets if pet.id is not None)

    async def test_get_pet_by_id(self, pet_api_client: PetApi) -> None:
        """Test case for get_pet_by_id

        Get Pet By Id  # noqa: E501
        """
        created_pet = await pet_api_client.add_pet(
            self._build_pet_create(name="integration-get-pet")
        )
        assert created_pet.id is not None

        fetched_pet = await pet_api_client.get_pet_by_id(created_pet.id)

        assert isinstance(fetched_pet, Pet)
        assert fetched_pet.id == created_pet.id
        assert fetched_pet.name == "integration-get-pet"

    async def test_update_pet(self, pet_api_client: PetApi) -> None:
        """Test case for update_pet

        Update Pet  # noqa: E501
        """
        created_pet = await pet_api_client.add_pet(
            self._build_pet_create(name="integration-update-pet")
        )
        assert created_pet.id is not None

        updated_pet = await pet_api_client.update_pet(
            PetUpdate(
                id=created_pet.id,
                name="integration-update-pet-new",
                photoUrls=created_pet.photo_urls,
                status=PetStatus.PENDING,
            )
        )

        assert isinstance(updated_pet, Pet)
        assert updated_pet.id == created_pet.id
        assert updated_pet.name == "integration-update-pet-new"
        assert updated_pet.status == PetStatus.PENDING

    async def test_update_pet_with_form(self, pet_api_client: PetApi) -> None:
        """Test case for update_pet_with_form

        Update Pet With Form  # noqa: E501
        """
        created_pet = await pet_api_client.add_pet(
            self._build_pet_create(name="integration-form-pet")
        )
        assert created_pet.id is not None

        updated_pet = await pet_api_client.update_pet_with_form(
            pet_id=created_pet.id,
            name="integration-form-pet-new",
            status=PetStatus.SOLD.value,
        )

        assert isinstance(updated_pet, Pet)
        assert updated_pet.id == created_pet.id
        assert updated_pet.name == "integration-form-pet-new"
        assert updated_pet.status == PetStatus.SOLD

    @pytest.mark.xfail(reason="Investigation Pending")
    async def test_upload_file(self, pet_api_client: PetApi) -> None:
        """Test case for upload_file

        Upload File  # noqa: E501
        """
        created_pet = await pet_api_client.add_pet(
            self._build_pet_create(name="integration-upload-pet")
        )
        assert created_pet.id is not None

        # Current generated client maps multipart file field as StrictStr,
        # while the service expects UploadFile, so this call is expected to fail.
        await pet_api_client.upload_file(
            pet_id=created_pet.id,
            file="test-image-content",
            additional_metadata="integration-upload",
        )
