# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest
import pytest_asyncio
from petstore_openapi_client.exceptions import ApiException

from petstore_openapi_client.api.store_api import StoreApi  # noqa: E501
from petstore_openapi_client import ApiClient
from petstore_openapi_client.models.order import Order
from petstore_openapi_client.models.order_create import OrderCreate
from petstore_openapi_client.models.order_status import OrderStatus


@pytest_asyncio.fixture()
async def store_api_client(api_client: ApiClient):
    api = StoreApi(api_client=api_client)
    yield api


@pytest.mark.asyncio
class TestStoreApi:
    """StoreApi unit test stubs"""

    @staticmethod
    def _build_order_create() -> OrderCreate:
        return OrderCreate(pet_id=1, quantity=1, status=OrderStatus.PLACED, complete=False)

    async def test_delete_order_api_v1_store_order_order_id_delete(self, store_api_client: StoreApi) -> None:
        """Test case for delete_order_api_v1_store_order_order_id_delete

        Delete Order  # noqa: E501
        """
        created_order = await store_api_client.place_order_api_v1_store_order_post(
            self._build_order_create()
        )
        assert created_order.id is not None

        delete_result = await store_api_client.delete_order_api_v1_store_order_order_id_delete(
            created_order.id
        )

        assert isinstance(delete_result, dict)
        assert delete_result

        with pytest.raises(ApiException) as exc_info:
            await store_api_client.get_order_by_id_api_v1_store_order_order_id_get(
                created_order.id
            )
        assert exc_info.value.status == 404

    async def test_get_inventory_api_v1_store_inventory_get(self, store_api_client: StoreApi) -> None:
        """Test case for get_inventory_api_v1_store_inventory_get

        Get Inventory  # noqa: E501
        """
        inventory = await store_api_client.get_inventory_api_v1_store_inventory_get()

        assert isinstance(inventory, list)
        assert all(isinstance(item, Order) for item in inventory)


    async def test_get_order_by_id_api_v1_store_order_order_id_get(self, store_api_client: StoreApi) -> None:
        """Test case for get_order_by_id_api_v1_store_order_order_id_get

        Get Order By Id  # noqa: E501
        """
        created_order = await store_api_client.place_order_api_v1_store_order_post(
            self._build_order_create()
        )
        assert created_order.id is not None

        fetched_order = await store_api_client.get_order_by_id_api_v1_store_order_order_id_get(
            created_order.id
        )

        assert isinstance(fetched_order, Order)
        assert fetched_order.id == created_order.id
        assert fetched_order.quantity == 1

    async def test_place_order_api_v1_store_order_post(self, store_api_client: StoreApi) -> None:
        """Test case for place_order_api_v1_store_order_post

        Place Order  # noqa: E501
        """
        created_order = await store_api_client.place_order_api_v1_store_order_post(
            self._build_order_create()
        )

        assert isinstance(created_order, Order)
        assert created_order.id is not None
        assert created_order.quantity == 1
        assert created_order.status == OrderStatus.PLACED

