# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest

from openapi_client.models.category import Category
from openapi_client.models.pet_update import PetUpdate
from openapi_client.models.pet_status import PetStatus
from openapi_client.models.tag import Tag

class TestPetUpdate:
    """PetUpdate model tests."""

    def test_pet_update_requires_name_and_id(self) -> None:
        with pytest.raises(ValueError):
            PetUpdate(name="pet")

        with pytest.raises(ValueError):
            PetUpdate(id=1)

    def test_pet_update_with_required_only(self) -> None:
        pet = PetUpdate(name="pet-required", id=10)

        assert pet.name == "pet-required"
        assert pet.id == 10

    def test_pet_update_with_optional_fields(self) -> None:
        pet = PetUpdate(
            id=11,
            name="pet-optional",
            photo_urls=["https://example.com/photo.png"],
            category=Category(id=1, name="cats"),
            tags=[Tag(id=2, name="young")],
            status=PetStatus.PENDING,
        )

        assert pet.photo_urls == ["https://example.com/photo.png"]
        assert pet.category is not None
        assert pet.category.name == "cats"
        assert pet.tags is not None
        assert pet.tags[0].name == "young"
        assert pet.status == PetStatus.PENDING
