# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest

from openapi_client.models.pet_status import PetStatus

class TestPetStatus:
    """PetStatus unit test stubs"""

    @pytest.mark.skip(reason="Generated stub test - implement assertions")
    def testPetStatus(self):
        """Test PetStatus"""
        # inst = PetStatus()
        # assert inst
