# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



from openapi_client.api.health_api import HealthApi  # noqa: E501


class TestHealthApi:
    """HealthApi unit test stubs"""

    def setup_method(self) -> None:
        self.api = HealthApi()

    def teardown_method(self) -> None:
        self.api.api_client.close()

    def test_health_check_health_get(self) -> None:
        """Test case for health_check_health_get

        Health Check  # noqa: E501
        """
        pass

