# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest

from openapi_client.models.pet_update import PetUpdate

class TestPetUpdate:
    """PetUpdate unit test stubs"""

    def make_instance(self, include_optional: bool) -> PetUpdate:
        """Create an PetUpdate instance for testing.

        Args:
            include_optional (bool):
                If False, only the required parameters should be included.
                If True, both required and optional parameters should be included.

        Returns:
            PetUpdate: A populated PetUpdate model instance.

        TODO:
            Replace the placeholder example values below with meaningful test data
            appropriate for your API. These are only illustrative defaults.

        Example:
            if include_optional:
                return PetUpdate(
                    name = '0',
                    photo_urls = [
                    ''
                    ],
                    category = openapi_client.models.category.Category(
                    id = 56, 
                    name = '', ),
                    tags = [
                    openapi_client.models.tag.Tag(
                        id = 56, 
                        name = '', )
                    ],
                    status = 'available',
                    id = 56
                )
            else:
                return PetUpdate(
                    name = '0',
                    id = 56,
            )
        """
        raise NotImplementedError("Populate example values before using this helper.")

    @pytest.mark.skip(reason="Generated stub test - implement assertions")
    def testPetUpdate(self):
        """Test PetUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)
