# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.user_api import UserApi  # noqa: E501


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_create_user_api_v1_user_post(self) -> None:
        """Test case for create_user_api_v1_user_post

        Create User  # noqa: E501
        """
        pass

    def test_create_users_with_list_api_v1_user_create_with_list_post(self) -> None:
        """Test case for create_users_with_list_api_v1_user_create_with_list_post

        Create Users With List  # noqa: E501
        """
        pass

    def test_delete_user_api_v1_user_username_delete(self) -> None:
        """Test case for delete_user_api_v1_user_username_delete

        Delete User  # noqa: E501
        """
        pass

    def test_get_user_by_name_api_v1_user_username_get(self) -> None:
        """Test case for get_user_by_name_api_v1_user_username_get

        Get User By Name  # noqa: E501
        """
        pass

    def test_login_user_api_v1_user_login_get(self) -> None:
        """Test case for login_user_api_v1_user_login_get

        Login User  # noqa: E501
        """
        pass

    def test_logout_user_api_v1_user_logout_get(self) -> None:
        """Test case for logout_user_api_v1_user_logout_get

        Logout User  # noqa: E501
        """
        pass

    def test_update_user_api_v1_user_username_put(self) -> None:
        """Test case for update_user_api_v1_user_username_put

        Update User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
