# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from openapi_client.models.pet_status import PetStatus  # noqa: E501

class TestPetStatus:
    """PetStatus unit test stubs"""

    def setup_method(self):
        pass

    def teardown_method(self):
        pass

    def testPetStatus(self):
        """Test PetStatus"""
        # inst = PetStatus()
