# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from petstore_openapi_client.models.user_update import UserUpdate

class TestUserUpdate:
    """UserUpdate model tests."""

    def test_user_update_allows_empty_instance(self) -> None:
        user_update = UserUpdate()

        assert user_update.username is None
        assert user_update.password is None

    def test_user_update_with_optional_fields(self) -> None:
        user_update = UserUpdate(
            username="updated-user",
            first_name="Updated",
            last_name="User",
            email="updated@example.com",
            phone="555-3000",
            user_status=3,
            password="new-secret",
        )

        assert user_update.username == "updated-user"
        assert user_update.first_name == "Updated"
        assert user_update.last_name == "User"
        assert user_update.email == "updated@example.com"
        assert user_update.phone == "555-3000"
        assert user_update.user_status == 3
        assert user_update.password == "new-secret"

    def test_user_update_serialization_round_trip(self) -> None:
        user_update = UserUpdate(
            username="updated-user",
            first_name="Updated",
            last_name="User",
            email="updated@example.com",
            phone="555-3000",
            user_status=3,
            password="new-secret",
        )

        as_dict = user_update.to_dict()
        assert as_dict["username"] == "updated-user"
        assert as_dict["password"] == "new-secret"

        from_dict = UserUpdate.from_dict(as_dict)
        assert from_dict.username == user_update.username
        assert from_dict.password == user_update.password

        as_json = user_update.to_json()
        from_json = UserUpdate.from_json(as_json)
        assert from_json.username == user_update.username
        assert from_json.password == user_update.password

        assert "updated-user" in user_update.to_str()
