# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import annotations

import pytest

from petstore_openapi_client.models.health_details import HealthDetails

class TestHealthDetails:
    """HealthDetails unit test stubs"""

    def make_instance(self, include_optional: bool) -> HealthDetails:
        """Create an HealthDetails instance for testing.

        Args:
            include_optional (bool):
                If False, only the required parameters should be included.
                If True, both required and optional parameters should be included.

        Returns:
            HealthDetails: A populated HealthDetails model instance.

        TODO:
            Replace the placeholder example values below with meaningful test data
            appropriate for your API. These are only illustrative defaults.

        Example:
            if include_optional:
                return HealthDetails(
                    version = '',
                    build_date = '',
                    git_commit_sha = ''
                )
            else:
                return HealthDetails(
                    version = '',
                    build_date = '',
                    git_commit_sha = '',
            )
        """
        raise NotImplementedError("Populate example values before using this helper.")

    @pytest.mark.skip(reason="Generated stub test - implement assertions")
    def testHealthDetails(self):
        """Test HealthDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)
