# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from openapi_client.models.order_status import OrderStatus

class TestOrderStatus:
    """OrderStatus enum tests."""

    def test_order_status_values(self) -> None:
        assert OrderStatus.PLACED.value == "placed"
        assert OrderStatus.APPROVED.value == "approved"
        assert OrderStatus.DELIVERED.value == "delivered"

    def test_order_status_from_value(self) -> None:
        assert OrderStatus("approved") == OrderStatus.APPROVED
