# coding: utf-8

# flake8: noqa

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Contact: ramalc.ms@outlook.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import annotations


__version__ = "0.0.0"

# Define package exports
__all__ = [
    "HealthApi",
    "PetApi",
    "StoreApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Category",
    "HTTPValidationError",
    "HealthDetails",
    "HealthResponse",
    "LocationInner",
    "Order",
    "OrderCreate",
    "OrderStatus",
    "Pet",
    "PetCreate",
    "PetStatus",
    "PetUpdate",
    "Tag",
    "User",
    "UserCreate",
    "UserUpdate",
    "ValidationError",
]

# import apis into sdk package
from petstore_openapi_client.api.health_api import HealthApi as HealthApi
from petstore_openapi_client.api.pet_api import PetApi as PetApi
from petstore_openapi_client.api.store_api import StoreApi as StoreApi
from petstore_openapi_client.api.user_api import UserApi as UserApi

# import ApiClient
from petstore_openapi_client.api_response import ApiResponse as ApiResponse
from petstore_openapi_client.api_client import ApiClient as ApiClient
from petstore_openapi_client.configuration import Configuration as Configuration
from petstore_openapi_client.exceptions import OpenApiException as OpenApiException
from petstore_openapi_client.exceptions import ApiTypeError as ApiTypeError
from petstore_openapi_client.exceptions import ApiValueError as ApiValueError
from petstore_openapi_client.exceptions import ApiKeyError as ApiKeyError
from petstore_openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from petstore_openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from petstore_openapi_client.models.category import Category as Category
from petstore_openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from petstore_openapi_client.models.health_details import HealthDetails as HealthDetails
from petstore_openapi_client.models.health_response import HealthResponse as HealthResponse
from petstore_openapi_client.models.location_inner import LocationInner as LocationInner
from petstore_openapi_client.models.order import Order as Order
from petstore_openapi_client.models.order_create import OrderCreate as OrderCreate
from petstore_openapi_client.models.order_status import OrderStatus as OrderStatus
from petstore_openapi_client.models.pet import Pet as Pet
from petstore_openapi_client.models.pet_create import PetCreate as PetCreate
from petstore_openapi_client.models.pet_status import PetStatus as PetStatus
from petstore_openapi_client.models.pet_update import PetUpdate as PetUpdate
from petstore_openapi_client.models.tag import Tag as Tag
from petstore_openapi_client.models.user import User as User
from petstore_openapi_client.models.user_create import UserCreate as UserCreate
from petstore_openapi_client.models.user_update import UserUpdate as UserUpdate
from petstore_openapi_client.models.validation_error import ValidationError as ValidationError
