# coding: utf-8

# flake8: noqa
"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.category import Category
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.location_inner import LocationInner
from openapi_client.models.order import Order
from openapi_client.models.order_create import OrderCreate
from openapi_client.models.order_status import OrderStatus
from openapi_client.models.pet import Pet
from openapi_client.models.pet_create import PetCreate
from openapi_client.models.pet_status import PetStatus
from openapi_client.models.pet_update import PetUpdate
from openapi_client.models.tag import Tag
from openapi_client.models.user import User
from openapi_client.models.user_create import UserCreate
from openapi_client.models.user_update import UserUpdate
from openapi_client.models.validation_error import ValidationError
