# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Contact: ramalc.ms@outlook.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import annotations


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, StrictBool, StrictInt
from pydantic import ConfigDict, field_validator
from openapi_client.assertions import AssertableModelMixin
from openapi_client.models.order_status import OrderStatus

class OrderCreate(AssertableModelMixin, BaseModel):
    """
    Schema for creating a new order.  # noqa: E501
    """
    pet_id: Optional[StrictInt] = None
    quantity: Optional[StrictInt] = None
    ship_date: Optional[datetime] = None
    status: Optional[OrderStatus] = None
    complete: Optional[StrictBool] = None
    __properties = ["pet_id", "quantity", "ship_date", "status", "complete"]

    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OrderCreate:
        """Create an instance of OrderCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if pet_id (nullable) is None
        # and __fields_set__ contains the field
        if self.pet_id is None and "pet_id" in self.model_fields_set:
            _dict['pet_id'] = None

        # set to None if quantity (nullable) is None
        # and __fields_set__ contains the field
        if self.quantity is None and "quantity" in self.model_fields_set:
            _dict['quantity'] = None

        # set to None if ship_date (nullable) is None
        # and __fields_set__ contains the field
        if self.ship_date is None and "ship_date" in self.model_fields_set:
            _dict['ship_date'] = None

        # set to None if status (nullable) is None
        # and __fields_set__ contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if complete (nullable) is None
        # and __fields_set__ contains the field
        if self.complete is None and "complete" in self.model_fields_set:
            _dict['complete'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OrderCreate:
        """Create an instance of OrderCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OrderCreate.model_validate(obj)

        _obj = OrderCreate.model_validate({
            "pet_id": obj.get("pet_id"),
            "quantity": obj.get("quantity"),
            "ship_date": obj.get("ship_date"),
            "status": obj.get("status"),
            "complete": obj.get("complete")
        })
        return _obj


