# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Contact: ramalc.ms@outlook.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class PetStatus(str, Enum):
    """
    Pet availability status.
    """

    """
    allowed enum values
    """
    AVAILABLE = 'available'
    PENDING = 'pending'
    SOLD = 'sold'

    @classmethod
    def from_json(cls, json_str: str) -> PetStatus:
        """Create an instance of PetStatus from a JSON string"""
        return PetStatus(json.loads(json_str))


