# coding: utf-8

# flake8: noqa
"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Contact: ramalc.ms@outlook.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import annotations


# import models into model package
from petstore_openapi_client.models.category import Category
from petstore_openapi_client.models.http_validation_error import HTTPValidationError
from petstore_openapi_client.models.location_inner import LocationInner
from petstore_openapi_client.models.order import Order
from petstore_openapi_client.models.order_create import OrderCreate
from petstore_openapi_client.models.order_status import OrderStatus
from petstore_openapi_client.models.pet import Pet
from petstore_openapi_client.models.pet_create import PetCreate
from petstore_openapi_client.models.pet_status import PetStatus
from petstore_openapi_client.models.pet_update import PetUpdate
from petstore_openapi_client.models.tag import Tag
from petstore_openapi_client.models.user import User
from petstore_openapi_client.models.user_create import UserCreate
from petstore_openapi_client.models.user_update import UserUpdate
from petstore_openapi_client.models.validation_error import ValidationError
