# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Contact: ramalc.ms@outlook.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import annotations


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from pydantic import ConfigDict, field_validator
from petstore_openapi_client.assertions import AssertableModelMixin

class HealthDetails(AssertableModelMixin, BaseModel):
    """
    Additional health metadata.  Attributes:     version: Application version.     build_date: Build date string.     git_commit_sha: Git commit SHA.  # noqa: E501
    """
    version: StrictStr = Field(...)
    build_date: StrictStr = Field(...)
    git_commit_sha: StrictStr = Field(...)
    __properties = ["version", "build_date", "git_commit_sha"]

    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> HealthDetails:
        """Create an instance of HealthDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> HealthDetails:
        """Create an instance of HealthDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return HealthDetails.model_validate(obj)

        _obj = HealthDetails.model_validate({
            "version": obj.get("version"),
            "build_date": obj.get("build_date"),
            "git_commit_sha": obj.get("git_commit_sha")
        })
        return _obj


