# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Contact: ramalc.ms@outlook.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import annotations


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from pydantic import ConfigDict, field_validator
from petstore_openapi_client.assertions import AssertableModelMixin
from petstore_openapi_client.models.health_details import HealthDetails

class HealthResponse(AssertableModelMixin, BaseModel):
    """
    Health check response payload.  Attributes:     status: Service status string.     mode: Storage mode.     details: Build and version metadata.  # noqa: E501
    """
    status: StrictStr = Field(...)
    mode: StrictStr = Field(...)
    details: HealthDetails = Field(...)
    __properties = ["status", "mode", "details"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('ok',):
            raise ValueError("must be one of enum values ('ok')")
        return value

    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> HealthResponse:
        """Create an instance of HealthResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of details
        if self.details:
            _dict['details'] = self.details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> HealthResponse:
        """Create an instance of HealthResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return HealthResponse.model_validate(obj)

        _obj = HealthResponse.model_validate({
            "status": obj.get("status"),
            "mode": obj.get("mode"),
            "details": HealthDetails.from_dict(obj.get("details")) if obj.get("details") is not None else None
        })
        return _obj


