# coding: utf-8

"""
Petstore API

A production-ready Petstore API built with FastAPI.

The version of the OpenAPI document: v1
Contact: ramalc.ms@outlook.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations


import json
import re  # noqa: F401
from aenum import Enum


class OrderStatus(str, Enum):
    """
    Order fulfillment status.
    """

    """
    allowed enum values
    """
    PLACED = "placed"
    APPROVED = "approved"
    DELIVERED = "delivered"

    @classmethod
    def from_json(cls, json_str: str) -> OrderStatus:
        """Create an instance of OrderStatus from a JSON string"""
        return OrderStatus(json.loads(json_str))
