# coding: utf-8

"""
Petstore API

A production-ready Petstore API built with FastAPI.

The version of the OpenAPI document: v1
Contact: ramalc.ms@outlook.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, conlist, constr
from pydantic import ConfigDict
from petstore_openapi_client.assertions import AssertableModelMixin
from petstore_openapi_client.models.category import Category
from petstore_openapi_client.models.pet_status import PetStatus
from petstore_openapi_client.models.tag import Tag


class PetCreate(AssertableModelMixin, BaseModel):
    """
    Schema for creating a new pet.  # noqa: E501
    """

    name: constr(strict=True, min_length=1) = Field(...)
    photo_urls: Optional[conlist(StrictStr)] = Field(default=None, alias="photoUrls")
    category: Optional[Category] = None
    tags: Optional[conlist(Tag)] = None
    status: Optional[PetStatus] = None
    __properties = ["name", "photoUrls", "category", "tags", "status"]

    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PetCreate:
        """Create an instance of PetCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.model_dump(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of category
        if self.category:
            _dict["category"] = self.category.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict["tags"] = _items
        # set to None if category (nullable) is None
        # and __fields_set__ contains the field
        if self.category is None and "category" in self.model_fields_set:
            _dict["category"] = None

        # set to None if tags (nullable) is None
        # and __fields_set__ contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict["tags"] = None

        # set to None if status (nullable) is None
        # and __fields_set__ contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict["status"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PetCreate:
        """Create an instance of PetCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PetCreate.model_validate(obj)

        _obj = PetCreate.model_validate(
            {
                "name": obj.get("name"),
                "photo_urls": obj.get("photoUrls"),
                "category": Category.from_dict(obj.get("category"))
                if obj.get("category") is not None
                else None,
                "tags": [Tag.from_dict(_item) for _item in obj.get("tags")]
                if obj.get("tags") is not None
                else None,
                "status": obj.get("status"),
            }
        )
        return _obj
