# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Contact: ramalc.ms@outlook.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import annotations


import re  # noqa: F401
import io
import warnings

from aenum import Enum
from pydantic import validate_arguments, ValidationError
from typing import overload, Optional, Union, Awaitable

from typing_extensions import Annotated
from pydantic import Field, StrictInt, StrictStr, conlist

from typing import Any, Dict, List, Optional

from openapi_client.models.pet import Pet
from openapi_client.models.pet_create import PetCreate
from openapi_client.models.pet_update import PetUpdate
from openapi_client.models.pet_status import PetStatus

from openapi_client.api_client import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class PetApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    async def add_pet_api_v1_pet_post(self, pet_create : PetCreate, **kwargs) -> Pet:  # noqa: E501
        """Add Pet  # noqa: E501

        Add a new pet to the store.  Args:     pet: Pet data from request body.     service: Injected PetService.  Returns:     The created pet.  # noqa: E501

        :param pet_create: (required)
        :type pet_create: PetCreate
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Pet
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the add_pet_api_v1_pet_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.add_pet_api_v1_pet_post_with_http_info(pet_create, **kwargs)  # noqa: E501

    @validate_arguments
    async def add_pet_api_v1_pet_post_with_http_info(self, pet_create : PetCreate, **kwargs) -> ApiResponse:  # noqa: E501
        """Add Pet  # noqa: E501

        Add a new pet to the store.  Args:     pet: Pet data from request body.     service: Injected PetService.  Returns:     The created pet.  # noqa: E501

        :param pet_create: (required)
        :type pet_create: PetCreate
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Pet, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'pet_create'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_pet_api_v1_pet_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['pet_create'] is not None:
            _body_params = _params['pet_create']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "Pet",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/pet', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def add_pet_api_v1_pet_post_without_validation(self, pet_create=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Add Pet — without pydantic validation  # noqa: E501

        Like ``add_pet_api_v1_pet_post_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``add_pet_api_v1_pet_post_with_http_info`` are forwarded verbatim.

        :param pet_create: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.add_pet_api_v1_pet_post_with_http_info.__wrapped__
        return await _impl(self, pet_create, **kwargs)

    @validate_arguments
    async def delete_pet_api_v1_pet_pet_id_delete(self, pet_id : StrictInt, **kwargs) -> Dict[str, str]:  # noqa: E501
        """Delete Pet  # noqa: E501

        Delete a pet.  Args:     pet_id: The pet's unique identifier.     service: Injected PetService.  Returns:     Confirmation message.  # noqa: E501

        :param pet_id: (required)
        :type pet_id: int
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Dict[str, str]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the delete_pet_api_v1_pet_pet_id_delete_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.delete_pet_api_v1_pet_pet_id_delete_with_http_info(pet_id, **kwargs)  # noqa: E501

    @validate_arguments
    async def delete_pet_api_v1_pet_pet_id_delete_with_http_info(self, pet_id : StrictInt, **kwargs) -> ApiResponse:  # noqa: E501
        """Delete Pet  # noqa: E501

        Delete a pet.  Args:     pet_id: The pet's unique identifier.     service: Injected PetService.  Returns:     Confirmation message.  # noqa: E501

        :param pet_id: (required)
        :type pet_id: int
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Dict[str, str], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'pet_id'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_pet_api_v1_pet_pet_id_delete" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['pet_id'] is not None:
            _path_params['pet_id'] = _params['pet_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "Dict[str, str]",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/pet/{pet_id}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def delete_pet_api_v1_pet_pet_id_delete_without_validation(self, pet_id=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Delete Pet — without pydantic validation  # noqa: E501

        Like ``delete_pet_api_v1_pet_pet_id_delete_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``delete_pet_api_v1_pet_pet_id_delete_with_http_info`` are forwarded verbatim.

        :param pet_id: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.delete_pet_api_v1_pet_pet_id_delete_with_http_info.__wrapped__
        return await _impl(self, pet_id, **kwargs)

    @validate_arguments
    async def find_pets_by_status_api_v1_pet_find_by_status_get(self, status : Annotated[Optional[PetStatus], Field(description="Status values to filter by")] = None, **kwargs) -> List[Pet]:  # noqa: E501
        """Find Pets By Status  # noqa: E501

        Find pets by status.  Args:     status: Availability status to filter by.     service: Injected PetService.  Returns:     List of pets matching the given status.  # noqa: E501

        :param status: Status values to filter by
        :type status: PetStatus
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[Pet]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the find_pets_by_status_api_v1_pet_find_by_status_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.find_pets_by_status_api_v1_pet_find_by_status_get_with_http_info(status, **kwargs)  # noqa: E501

    @validate_arguments
    async def find_pets_by_status_api_v1_pet_find_by_status_get_with_http_info(self, status : Annotated[Optional[PetStatus], Field(description="Status values to filter by")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Find Pets By Status  # noqa: E501

        Find pets by status.  Args:     status: Availability status to filter by.     service: Injected PetService.  Returns:     List of pets matching the given status.  # noqa: E501

        :param status: Status values to filter by
        :type status: PetStatus
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[Pet], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'status'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method find_pets_by_status_api_v1_pet_find_by_status_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('status') is not None:  # noqa: E501
            if isinstance(_params['status'], Enum):
                _query_params.append(('status', _params['status'].value))
            else:
                _query_params.append(('status', _params['status']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "List[Pet]",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/pet/findByStatus', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def find_pets_by_status_api_v1_pet_find_by_status_get_without_validation(self, status=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Find Pets By Status — without pydantic validation  # noqa: E501

        Like ``find_pets_by_status_api_v1_pet_find_by_status_get_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``find_pets_by_status_api_v1_pet_find_by_status_get_with_http_info`` are forwarded verbatim.

        :param status: Status values to filter by (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.find_pets_by_status_api_v1_pet_find_by_status_get_with_http_info.__wrapped__
        return await _impl(self, status, **kwargs)

    @validate_arguments
    async def find_pets_by_tags_api_v1_pet_find_by_tags_get(self, tags : Annotated[conlist(StrictStr), Field(..., description="Tags to filter by")], **kwargs) -> List[Pet]:  # noqa: E501
        """Find Pets By Tags  # noqa: E501

        Find pets by tags.  Args:     tags: Tag names to filter by.     service: Injected PetService.  Returns:     List of pets matching any of the given tags.  # noqa: E501

        :param tags: Tags to filter by (required)
        :type tags: List[str]
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[Pet]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the find_pets_by_tags_api_v1_pet_find_by_tags_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.find_pets_by_tags_api_v1_pet_find_by_tags_get_with_http_info(tags, **kwargs)  # noqa: E501

    @validate_arguments
    async def find_pets_by_tags_api_v1_pet_find_by_tags_get_with_http_info(self, tags : Annotated[conlist(StrictStr), Field(..., description="Tags to filter by")], **kwargs) -> ApiResponse:  # noqa: E501
        """Find Pets By Tags  # noqa: E501

        Find pets by tags.  Args:     tags: Tag names to filter by.     service: Injected PetService.  Returns:     List of pets matching any of the given tags.  # noqa: E501

        :param tags: Tags to filter by (required)
        :type tags: List[str]
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[Pet], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'tags'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method find_pets_by_tags_api_v1_pet_find_by_tags_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('tags') is not None:  # noqa: E501
            if isinstance(_params['tags'], Enum):
                _query_params.append(('tags', _params['tags']))
            else:
                _query_params.append(('tags', _params['tags']))
            _collection_formats['tags'] = 'multi'

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "List[Pet]",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/pet/findByTags', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def find_pets_by_tags_api_v1_pet_find_by_tags_get_without_validation(self, tags=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Find Pets By Tags — without pydantic validation  # noqa: E501

        Like ``find_pets_by_tags_api_v1_pet_find_by_tags_get_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``find_pets_by_tags_api_v1_pet_find_by_tags_get_with_http_info`` are forwarded verbatim.

        :param tags: Tags to filter by (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.find_pets_by_tags_api_v1_pet_find_by_tags_get_with_http_info.__wrapped__
        return await _impl(self, tags, **kwargs)

    @validate_arguments
    async def get_pet_by_id_api_v1_pet_pet_id_get(self, pet_id : StrictInt, **kwargs) -> Pet:  # noqa: E501
        """Get Pet By Id  # noqa: E501

        Find pet by ID.  Args:     pet_id: The pet's unique identifier.     service: Injected PetService.  Returns:     The pet with the given ID.  # noqa: E501

        :param pet_id: (required)
        :type pet_id: int
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Pet
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_pet_by_id_api_v1_pet_pet_id_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.get_pet_by_id_api_v1_pet_pet_id_get_with_http_info(pet_id, **kwargs)  # noqa: E501

    @validate_arguments
    async def get_pet_by_id_api_v1_pet_pet_id_get_with_http_info(self, pet_id : StrictInt, **kwargs) -> ApiResponse:  # noqa: E501
        """Get Pet By Id  # noqa: E501

        Find pet by ID.  Args:     pet_id: The pet's unique identifier.     service: Injected PetService.  Returns:     The pet with the given ID.  # noqa: E501

        :param pet_id: (required)
        :type pet_id: int
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Pet, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'pet_id'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_pet_by_id_api_v1_pet_pet_id_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['pet_id'] is not None:
            _path_params['pet_id'] = _params['pet_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "Pet",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/pet/{pet_id}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def get_pet_by_id_api_v1_pet_pet_id_get_without_validation(self, pet_id=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Get Pet By Id — without pydantic validation  # noqa: E501

        Like ``get_pet_by_id_api_v1_pet_pet_id_get_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``get_pet_by_id_api_v1_pet_pet_id_get_with_http_info`` are forwarded verbatim.

        :param pet_id: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.get_pet_by_id_api_v1_pet_pet_id_get_with_http_info.__wrapped__
        return await _impl(self, pet_id, **kwargs)

    @validate_arguments
    async def update_pet_api_v1_pet_put(self, pet_update : PetUpdate, **kwargs) -> Pet:  # noqa: E501
        """Update Pet  # noqa: E501

        Update an existing pet.  Args:     pet: Updated pet data from request body.     service: Injected PetService.  Returns:     The updated pet.  # noqa: E501

        :param pet_update: (required)
        :type pet_update: PetUpdate
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Pet
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the update_pet_api_v1_pet_put_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.update_pet_api_v1_pet_put_with_http_info(pet_update, **kwargs)  # noqa: E501

    @validate_arguments
    async def update_pet_api_v1_pet_put_with_http_info(self, pet_update : PetUpdate, **kwargs) -> ApiResponse:  # noqa: E501
        """Update Pet  # noqa: E501

        Update an existing pet.  Args:     pet: Updated pet data from request body.     service: Injected PetService.  Returns:     The updated pet.  # noqa: E501

        :param pet_update: (required)
        :type pet_update: PetUpdate
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Pet, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'pet_update'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_pet_api_v1_pet_put" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['pet_update'] is not None:
            _body_params = _params['pet_update']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "Pet",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/pet', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def update_pet_api_v1_pet_put_without_validation(self, pet_update=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Update Pet — without pydantic validation  # noqa: E501

        Like ``update_pet_api_v1_pet_put_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``update_pet_api_v1_pet_put_with_http_info`` are forwarded verbatim.

        :param pet_update: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.update_pet_api_v1_pet_put_with_http_info.__wrapped__
        return await _impl(self, pet_update, **kwargs)

    @validate_arguments
    async def update_pet_with_form_api_v1_pet_pet_id_post(self, pet_id : StrictInt, name : Optional[StrictStr] = None, status : Optional[StrictStr] = None, **kwargs) -> Pet:  # noqa: E501
        """Update Pet With Form  # noqa: E501

        Update a pet with form data.  Args:     pet_id: The pet's unique identifier.     service: Injected PetService.     name: New name for the pet.     status: New status for the pet.  Returns:     The updated pet.  # noqa: E501

        :param pet_id: (required)
        :type pet_id: int
        :param name:
        :type name: str
        :param status:
        :type status: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Pet
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the update_pet_with_form_api_v1_pet_pet_id_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.update_pet_with_form_api_v1_pet_pet_id_post_with_http_info(pet_id, name, status, **kwargs)  # noqa: E501

    @validate_arguments
    async def update_pet_with_form_api_v1_pet_pet_id_post_with_http_info(self, pet_id : StrictInt, name : Optional[StrictStr] = None, status : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Update Pet With Form  # noqa: E501

        Update a pet with form data.  Args:     pet_id: The pet's unique identifier.     service: Injected PetService.     name: New name for the pet.     status: New status for the pet.  Returns:     The updated pet.  # noqa: E501

        :param pet_id: (required)
        :type pet_id: int
        :param name:
        :type name: str
        :param status:
        :type status: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Pet, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'pet_id',
            'name',
            'status'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_pet_with_form_api_v1_pet_pet_id_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['pet_id'] is not None:
            _path_params['pet_id'] = _params['pet_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        if _params['name'] is not None:
            _form_params.append(('name', _params['name']))

        if _params['status'] is not None:
            _form_params.append(('status', _params['status']))

        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/x-www-form-urlencoded']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "Pet",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/pet/{pet_id}', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def update_pet_with_form_api_v1_pet_pet_id_post_without_validation(self, pet_id=None, name=None, status=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Update Pet With Form — without pydantic validation  # noqa: E501

        Like ``update_pet_with_form_api_v1_pet_pet_id_post_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``update_pet_with_form_api_v1_pet_pet_id_post_with_http_info`` are forwarded verbatim.

        :param pet_id: (any value accepted — validation is skipped)
        :param name: (any value accepted — validation is skipped)
        :param status: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.update_pet_with_form_api_v1_pet_pet_id_post_with_http_info.__wrapped__
        return await _impl(self, pet_id, name, status, **kwargs)

    @validate_arguments
    async def upload_file_api_v1_pet_pet_id_upload_file_post(self, pet_id : StrictInt, file : Optional[StrictStr] = None, additional_metadata : Optional[StrictStr] = None, **kwargs) -> Dict[str, str]:  # noqa: E501
        """Upload File  # noqa: E501

        Upload an image for a pet.  Args:     pet_id: The pet's unique identifier.     service: Injected PetService.     file: The image file to upload.     additional_metadata: Optional metadata string.  Returns:     Confirmation message with file info.  # noqa: E501

        :param pet_id: (required)
        :type pet_id: int
        :param file:
        :type file: str
        :param additional_metadata:
        :type additional_metadata: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Dict[str, str]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the upload_file_api_v1_pet_pet_id_upload_file_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.upload_file_api_v1_pet_pet_id_upload_file_post_with_http_info(pet_id, file, additional_metadata, **kwargs)  # noqa: E501

    @validate_arguments
    async def upload_file_api_v1_pet_pet_id_upload_file_post_with_http_info(self, pet_id : StrictInt, file : Optional[StrictStr] = None, additional_metadata : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Upload File  # noqa: E501

        Upload an image for a pet.  Args:     pet_id: The pet's unique identifier.     service: Injected PetService.     file: The image file to upload.     additional_metadata: Optional metadata string.  Returns:     Confirmation message with file info.  # noqa: E501

        :param pet_id: (required)
        :type pet_id: int
        :param file:
        :type file: str
        :param additional_metadata:
        :type additional_metadata: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Dict[str, str], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'pet_id',
            'file',
            'additional_metadata'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method upload_file_api_v1_pet_pet_id_upload_file_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['pet_id'] is not None:
            _path_params['pet_id'] = _params['pet_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        if _params['file'] is not None:
            _form_params.append(('file', _params['file']))

        if _params['additional_metadata'] is not None:
            _form_params.append(('additional_metadata', _params['additional_metadata']))

        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['multipart/form-data']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "Dict[str, str]",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/pet/{pet_id}/uploadFile', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def upload_file_api_v1_pet_pet_id_upload_file_post_without_validation(self, pet_id=None, file=None, additional_metadata=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Upload File — without pydantic validation  # noqa: E501

        Like ``upload_file_api_v1_pet_pet_id_upload_file_post_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``upload_file_api_v1_pet_pet_id_upload_file_post_with_http_info`` are forwarded verbatim.

        :param pet_id: (any value accepted — validation is skipped)
        :param file: (any value accepted — validation is skipped)
        :param additional_metadata: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.upload_file_api_v1_pet_pet_id_upload_file_post_with_http_info.__wrapped__
        return await _impl(self, pet_id, file, additional_metadata, **kwargs)
