# coding: utf-8

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Contact: ramalc.ms@outlook.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import annotations


import re  # noqa: F401
import io
import warnings

from aenum import Enum
from pydantic import validate_arguments, ValidationError
from typing import overload, Optional, Union, Awaitable

from typing_extensions import Annotated
from pydantic import Field, StrictStr, conlist

from typing import Dict, List

from openapi_client.models.user import User
from openapi_client.models.user_create import UserCreate
from openapi_client.models.user_update import UserUpdate

from openapi_client.api_client import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class UserApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    async def create_user_api_v1_user_post(self, user_create : UserCreate, **kwargs) -> User:  # noqa: E501
        """Create User  # noqa: E501

        Create a new user.  Args:     user: User data from request body.     service: Injected UserService.  Returns:     The created user.  # noqa: E501

        :param user_create: (required)
        :type user_create: UserCreate
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: User
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the create_user_api_v1_user_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.create_user_api_v1_user_post_with_http_info(user_create, **kwargs)  # noqa: E501

    @validate_arguments
    async def create_user_api_v1_user_post_with_http_info(self, user_create : UserCreate, **kwargs) -> ApiResponse:  # noqa: E501
        """Create User  # noqa: E501

        Create a new user.  Args:     user: User data from request body.     service: Injected UserService.  Returns:     The created user.  # noqa: E501

        :param user_create: (required)
        :type user_create: UserCreate
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(User, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'user_create'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_user_api_v1_user_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['user_create'] is not None:
            _body_params = _params['user_create']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "User",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/user', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def create_user_api_v1_user_post_without_validation(self, user_create=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Create User — without pydantic validation  # noqa: E501

        Like ``create_user_api_v1_user_post_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``create_user_api_v1_user_post_with_http_info`` are forwarded verbatim.

        :param user_create: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.create_user_api_v1_user_post_with_http_info.__wrapped__
        return await _impl(self, user_create, **kwargs)

    @validate_arguments
    async def create_users_with_list_api_v1_user_create_with_list_post(self, user_create : conlist(UserCreate), **kwargs) -> List[User]:  # noqa: E501
        """Create Users With List  # noqa: E501

        Create users from a list.  Args:     users: List of user data from request body.     service: Injected UserService.  Returns:     List of created users.  # noqa: E501

        :param user_create: (required)
        :type user_create: List[UserCreate]
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[User]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the create_users_with_list_api_v1_user_create_with_list_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.create_users_with_list_api_v1_user_create_with_list_post_with_http_info(user_create, **kwargs)  # noqa: E501

    @validate_arguments
    async def create_users_with_list_api_v1_user_create_with_list_post_with_http_info(self, user_create : conlist(UserCreate), **kwargs) -> ApiResponse:  # noqa: E501
        """Create Users With List  # noqa: E501

        Create users from a list.  Args:     users: List of user data from request body.     service: Injected UserService.  Returns:     List of created users.  # noqa: E501

        :param user_create: (required)
        :type user_create: List[UserCreate]
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[User], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'user_create'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_users_with_list_api_v1_user_create_with_list_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['user_create'] is not None:
            _body_params = _params['user_create']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "List[User]",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/user/createWithList', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def create_users_with_list_api_v1_user_create_with_list_post_without_validation(self, user_create=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Create Users With List — without pydantic validation  # noqa: E501

        Like ``create_users_with_list_api_v1_user_create_with_list_post_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``create_users_with_list_api_v1_user_create_with_list_post_with_http_info`` are forwarded verbatim.

        :param user_create: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.create_users_with_list_api_v1_user_create_with_list_post_with_http_info.__wrapped__
        return await _impl(self, user_create, **kwargs)

    @validate_arguments
    async def delete_user_api_v1_user_username_delete(self, username : StrictStr, **kwargs) -> Dict[str, str]:  # noqa: E501
        """Delete User  # noqa: E501

        Delete user by username.  Args:     username: The user's unique username.     service: Injected UserService.  Returns:     Confirmation message.  # noqa: E501

        :param username: (required)
        :type username: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Dict[str, str]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the delete_user_api_v1_user_username_delete_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.delete_user_api_v1_user_username_delete_with_http_info(username, **kwargs)  # noqa: E501

    @validate_arguments
    async def delete_user_api_v1_user_username_delete_with_http_info(self, username : StrictStr, **kwargs) -> ApiResponse:  # noqa: E501
        """Delete User  # noqa: E501

        Delete user by username.  Args:     username: The user's unique username.     service: Injected UserService.  Returns:     Confirmation message.  # noqa: E501

        :param username: (required)
        :type username: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Dict[str, str], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'username'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_user_api_v1_user_username_delete" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['username'] is not None:
            _path_params['username'] = _params['username']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "Dict[str, str]",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/user/{username}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def delete_user_api_v1_user_username_delete_without_validation(self, username=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Delete User — without pydantic validation  # noqa: E501

        Like ``delete_user_api_v1_user_username_delete_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``delete_user_api_v1_user_username_delete_with_http_info`` are forwarded verbatim.

        :param username: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.delete_user_api_v1_user_username_delete_with_http_info.__wrapped__
        return await _impl(self, username, **kwargs)

    @validate_arguments
    async def get_user_by_name_api_v1_user_username_get(self, username : StrictStr, **kwargs) -> User:  # noqa: E501
        """Get User By Name  # noqa: E501

        Get user by username.  Args:     username: The user's username.     service: Injected UserService.  Returns:     The user with the given username.  # noqa: E501

        :param username: (required)
        :type username: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: User
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_user_by_name_api_v1_user_username_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.get_user_by_name_api_v1_user_username_get_with_http_info(username, **kwargs)  # noqa: E501

    @validate_arguments
    async def get_user_by_name_api_v1_user_username_get_with_http_info(self, username : StrictStr, **kwargs) -> ApiResponse:  # noqa: E501
        """Get User By Name  # noqa: E501

        Get user by username.  Args:     username: The user's username.     service: Injected UserService.  Returns:     The user with the given username.  # noqa: E501

        :param username: (required)
        :type username: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(User, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'username'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_user_by_name_api_v1_user_username_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['username'] is not None:
            _path_params['username'] = _params['username']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "User",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/user/{username}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def get_user_by_name_api_v1_user_username_get_without_validation(self, username=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Get User By Name — without pydantic validation  # noqa: E501

        Like ``get_user_by_name_api_v1_user_username_get_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``get_user_by_name_api_v1_user_username_get_with_http_info`` are forwarded verbatim.

        :param username: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.get_user_by_name_api_v1_user_username_get_with_http_info.__wrapped__
        return await _impl(self, username, **kwargs)

    @validate_arguments
    async def login_user_api_v1_user_login_get(self, username : Annotated[StrictStr, Field(..., description="The username for login")], password : Annotated[StrictStr, Field(..., description="The password for login")], **kwargs) -> Dict[str, str]:  # noqa: E501
        """Login User  # noqa: E501

        Log user into the system.  Args:     username: The username to log in with.     password: The password to log in with.     service: Injected UserService.  Returns:     Dict containing the session token.  # noqa: E501

        :param username: The username for login (required)
        :type username: str
        :param password: The password for login (required)
        :type password: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Dict[str, str]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the login_user_api_v1_user_login_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.login_user_api_v1_user_login_get_with_http_info(username, password, **kwargs)  # noqa: E501

    @validate_arguments
    async def login_user_api_v1_user_login_get_with_http_info(self, username : Annotated[StrictStr, Field(..., description="The username for login")], password : Annotated[StrictStr, Field(..., description="The password for login")], **kwargs) -> ApiResponse:  # noqa: E501
        """Login User  # noqa: E501

        Log user into the system.  Args:     username: The username to log in with.     password: The password to log in with.     service: Injected UserService.  Returns:     Dict containing the session token.  # noqa: E501

        :param username: The username for login (required)
        :type username: str
        :param password: The password for login (required)
        :type password: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Dict[str, str], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'username',
            'password'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method login_user_api_v1_user_login_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('username') is not None:  # noqa: E501
            if isinstance(_params['username'], Enum):
                _query_params.append(('username', _params['username']))
            else:
                _query_params.append(('username', _params['username']))

        if _params.get('password') is not None:  # noqa: E501
            if isinstance(_params['password'], Enum):
                _query_params.append(('password', _params['password']))
            else:
                _query_params.append(('password', _params['password']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "Dict[str, str]",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/user/login', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def login_user_api_v1_user_login_get_without_validation(self, username=None, password=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Login User — without pydantic validation  # noqa: E501

        Like ``login_user_api_v1_user_login_get_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``login_user_api_v1_user_login_get_with_http_info`` are forwarded verbatim.

        :param username: The username for login (any value accepted — validation is skipped)
        :param password: The password for login (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.login_user_api_v1_user_login_get_with_http_info.__wrapped__
        return await _impl(self, username, password, **kwargs)

    @validate_arguments
    async def logout_user_api_v1_user_logout_get(self, **kwargs) -> Dict[str, str]:  # noqa: E501
        """Logout User  # noqa: E501

        Log out current logged-in user session.  Args:     service: Injected UserService.  Returns:     Confirmation message.  # noqa: E501

        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Dict[str, str]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the logout_user_api_v1_user_logout_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.logout_user_api_v1_user_logout_get_with_http_info(**kwargs)  # noqa: E501

    @validate_arguments
    async def logout_user_api_v1_user_logout_get_with_http_info(self, **kwargs) -> ApiResponse:  # noqa: E501
        """Logout User  # noqa: E501

        Log out current logged-in user session.  Args:     service: Injected UserService.  Returns:     Confirmation message.  # noqa: E501

        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Dict[str, str], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method logout_user_api_v1_user_logout_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "Dict[str, str]",
        }

        return await self.api_client.call_api(
            '/api/v1/user/logout', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def logout_user_api_v1_user_logout_get_without_validation(self, **kwargs) -> ApiResponse:  # noqa: E501
        """Logout User — without pydantic validation  # noqa: E501

        Like ``logout_user_api_v1_user_logout_get_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``logout_user_api_v1_user_logout_get_with_http_info`` are forwarded verbatim.

        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.logout_user_api_v1_user_logout_get_with_http_info.__wrapped__
        return await _impl(self, **kwargs)

    @validate_arguments
    async def update_user_api_v1_user_username_put(self, username : StrictStr, user_update : UserUpdate, **kwargs) -> User:  # noqa: E501
        """Update User  # noqa: E501

        Update user by username.  Args:     username: The user's current username.     user: Updated user data.     service: Injected UserService.  Returns:     The updated user.  # noqa: E501

        :param username: (required)
        :type username: str
        :param user_update: (required)
        :type user_update: UserUpdate
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: User
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the update_user_api_v1_user_username_put_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.update_user_api_v1_user_username_put_with_http_info(username, user_update, **kwargs)  # noqa: E501

    @validate_arguments
    async def update_user_api_v1_user_username_put_with_http_info(self, username : StrictStr, user_update : UserUpdate, **kwargs) -> ApiResponse:  # noqa: E501
        """Update User  # noqa: E501

        Update user by username.  Args:     username: The user's current username.     user: Updated user data.     service: Injected UserService.  Returns:     The updated user.  # noqa: E501

        :param username: (required)
        :type username: str
        :param user_update: (required)
        :type user_update: UserUpdate
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(User, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'username',
            'user_update'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_user_api_v1_user_username_put" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['username'] is not None:
            _path_params['username'] = _params['username']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['user_update'] is not None:
            _body_params = _params['user_update']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['APIKeyHeader']  # noqa: E501

        _response_types_map = {
            '200': "User",
            '422': "HTTPValidationError",
        }

        return await self.api_client.call_api(
            '/api/v1/user/{username}', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    async def update_user_api_v1_user_username_put_without_validation(self, username=None, user_update=None, **kwargs) -> ApiResponse:  # noqa: E501
        """Update User — without pydantic validation  # noqa: E501

        Like ``update_user_api_v1_user_username_put_with_http_info`` but bypasses ``@validate_arguments``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``update_user_api_v1_user_username_put_with_http_info`` are forwarded verbatim.

        :param username: (any value accepted — validation is skipped)
        :param user_update: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_arguments on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.update_user_api_v1_user_username_put_with_http_info.__wrapped__
        return await _impl(self, username, user_update, **kwargs)
