# coding: utf-8

# flake8: noqa

"""
    Petstore API

    A production-ready Petstore API built with FastAPI.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "HealthApi",
    "PetApi",
    "StoreApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Category",
    "HTTPValidationError",
    "LocationInner",
    "Order",
    "OrderCreate",
    "OrderStatus",
    "Pet",
    "PetCreate",
    "PetStatus",
    "PetUpdate",
    "Tag",
    "User",
    "UserCreate",
    "UserUpdate",
    "ValidationError",
]

# import apis into sdk package
from openapi_client.api.health_api import HealthApi as HealthApi
from openapi_client.api.pet_api import PetApi as PetApi
from openapi_client.api.store_api import StoreApi as StoreApi
from openapi_client.api.user_api import UserApi as UserApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.category import Category as Category
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.location_inner import LocationInner as LocationInner
from openapi_client.models.order import Order as Order
from openapi_client.models.order_create import OrderCreate as OrderCreate
from openapi_client.models.order_status import OrderStatus as OrderStatus
from openapi_client.models.pet import Pet as Pet
from openapi_client.models.pet_create import PetCreate as PetCreate
from openapi_client.models.pet_status import PetStatus as PetStatus
from openapi_client.models.pet_update import PetUpdate as PetUpdate
from openapi_client.models.tag import Tag as Tag
from openapi_client.models.user import User as User
from openapi_client.models.user_create import UserCreate as UserCreate
from openapi_client.models.user_update import UserUpdate as UserUpdate
from openapi_client.models.validation_error import ValidationError as ValidationError
