# coding: utf-8

"""
Petstore API

A production-ready Petstore API built with FastAPI.

The version of the OpenAPI document: v1
Contact: ramalc.ms@outlook.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations


import re  # noqa: F401

from pydantic import validate_call

from petstore_openapi_client.models.health_response import HealthResponse

from petstore_openapi_client.api_client import ApiClient
from petstore_openapi_client.api_response import ApiResponse
from petstore_openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError,
)


class HealthApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    async def health_check_api_v1_health_get(self, **kwargs) -> HealthResponse:  # noqa: E501
        """Health Check  # noqa: E501

        Return service health status.  Returns:     Typed health payload with runtime mode and build metadata.  # noqa: E501

        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: HealthResponse
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the health_check_api_v1_health_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.health_check_api_v1_health_get_with_http_info(**kwargs)  # noqa: E501

    @validate_call
    async def health_check_api_v1_health_get_with_http_info(
        self, **kwargs
    ) -> ApiResponse:  # noqa: E501
        """Health Check  # noqa: E501

        Return service health status.  Returns:     Typed health payload with runtime mode and build metadata.  # noqa: E501

        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(HealthResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = []
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method health_check_api_v1_health_get" % _key
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            "200": "HealthResponse",
        }

        return await self.api_client.call_api(
            "/api/v1/health",
            "GET",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    async def health_check_api_v1_health_get_without_validation(
        self, **kwargs
    ) -> ApiResponse:  # noqa: E501
        """Health Check — without pydantic validation  # noqa: E501

        Like ``health_check_api_v1_health_get_with_http_info`` but bypasses ``@validate_call``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``health_check_api_v1_health_get_with_http_info`` are forwarded verbatim.

        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_call on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.health_check_api_v1_health_get_with_http_info.__wrapped__
        return await _impl(self, **kwargs)

    @validate_call
    async def health_check_health_get(self, **kwargs) -> HealthResponse:  # noqa: E501
        """Health Check  # noqa: E501

        Return service health status.  Returns:     Typed health payload with runtime mode and build metadata.  # noqa: E501

        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: HealthResponse
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the health_check_health_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.health_check_health_get_with_http_info(**kwargs)  # noqa: E501

    @validate_call
    async def health_check_health_get_with_http_info(self, **kwargs) -> ApiResponse:  # noqa: E501
        """Health Check  # noqa: E501

        Return service health status.  Returns:     Typed health payload with runtime mode and build metadata.  # noqa: E501

        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(HealthResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = []
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method health_check_health_get" % _key
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            "200": "HealthResponse",
        }

        return await self.api_client.call_api(
            "/health",
            "GET",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    async def health_check_health_get_without_validation(self, **kwargs) -> ApiResponse:  # noqa: E501
        """Health Check — without pydantic validation  # noqa: E501

        Like ``health_check_health_get_with_http_info`` but bypasses ``@validate_call``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``health_check_health_get_with_http_info`` are forwarded verbatim.

        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_call on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.health_check_health_get_with_http_info.__wrapped__
        return await _impl(self, **kwargs)
