# coding: utf-8

"""
Petstore API

A production-ready Petstore API built with FastAPI.

The version of the OpenAPI document: v1
Contact: ramalc.ms@outlook.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations


import re  # noqa: F401

from pydantic import validate_call

from pydantic import StrictInt

from typing import Dict, List

from petstore_openapi_client.models.order import Order
from petstore_openapi_client.models.order_create import OrderCreate

from petstore_openapi_client.api_client import ApiClient
from petstore_openapi_client.api_response import ApiResponse
from petstore_openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError,
)


class StoreApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    async def delete_order(self, order_id: StrictInt, **kwargs) -> Dict[str, str]:  # noqa: E501
        """Delete Order  # noqa: E501

        Delete purchase order by ID.  Args:     order_id: The order's unique identifier.     service: Injected OrderService.  Returns:     Confirmation message.  # noqa: E501

        :param order_id: (required)
        :type order_id: int
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Dict[str, str]
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the delete_order_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.delete_order_with_http_info(order_id, **kwargs)  # noqa: E501

    @validate_call
    async def delete_order_with_http_info(
        self, order_id: StrictInt, **kwargs
    ) -> ApiResponse:  # noqa: E501
        """Delete Order  # noqa: E501

        Delete purchase order by ID.  Args:     order_id: The order's unique identifier.     service: Injected OrderService.  Returns:     Confirmation message.  # noqa: E501

        :param order_id: (required)
        :type order_id: int
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Dict[str, str], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = ["order_id"]
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_order" % _key
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params["order_id"] is not None:
            _path_params["order_id"] = _params["order_id"]

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # authentication setting
        _auth_settings = ["APIKeyHeader"]  # noqa: E501

        _response_types_map = {
            "200": "Dict[str, str]",
            "422": "HTTPValidationError",
        }

        return await self.api_client.call_api(
            "/api/v1/store/order/{order_id}",
            "DELETE",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    async def delete_order_without_validation(
        self, order_id=None, **kwargs
    ) -> ApiResponse:  # noqa: E501
        """Delete Order — without pydantic validation  # noqa: E501

        Like ``delete_order_with_http_info`` but bypasses ``@validate_call``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``delete_order_with_http_info`` are forwarded verbatim.

        :param order_id: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_call on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.delete_order_with_http_info.__wrapped__
        return await _impl(self, order_id, **kwargs)

    @validate_call
    async def get_inventory(self, **kwargs) -> List[Order]:  # noqa: E501
        """Get Inventory  # noqa: E501

        Return all orders in the store.  Args:     service: Injected OrderService.  Returns:     List of all orders.  # noqa: E501

        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[Order]
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the get_inventory_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.get_inventory_with_http_info(**kwargs)  # noqa: E501

    @validate_call
    async def get_inventory_with_http_info(self, **kwargs) -> ApiResponse:  # noqa: E501
        """Get Inventory  # noqa: E501

        Return all orders in the store.  Args:     service: Injected OrderService.  Returns:     List of all orders.  # noqa: E501

        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[Order], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = []
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_inventory" % _key
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # authentication setting
        _auth_settings = ["APIKeyHeader"]  # noqa: E501

        _response_types_map = {
            "200": "List[Order]",
        }

        return await self.api_client.call_api(
            "/api/v1/store/inventory",
            "GET",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    async def get_inventory_without_validation(self, **kwargs) -> ApiResponse:  # noqa: E501
        """Get Inventory — without pydantic validation  # noqa: E501

        Like ``get_inventory_with_http_info`` but bypasses ``@validate_call``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``get_inventory_with_http_info`` are forwarded verbatim.

        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_call on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.get_inventory_with_http_info.__wrapped__
        return await _impl(self, **kwargs)

    @validate_call
    async def get_order_by_id(self, order_id: StrictInt, **kwargs) -> Order:  # noqa: E501
        """Get Order By Id  # noqa: E501

        Find purchase order by ID.  Args:     order_id: The order's unique identifier (1–10).     service: Injected OrderService.  Returns:     The order with the given ID.  # noqa: E501

        :param order_id: (required)
        :type order_id: int
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Order
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the get_order_by_id_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.get_order_by_id_with_http_info(order_id, **kwargs)  # noqa: E501

    @validate_call
    async def get_order_by_id_with_http_info(
        self, order_id: StrictInt, **kwargs
    ) -> ApiResponse:  # noqa: E501
        """Get Order By Id  # noqa: E501

        Find purchase order by ID.  Args:     order_id: The order's unique identifier (1–10).     service: Injected OrderService.  Returns:     The order with the given ID.  # noqa: E501

        :param order_id: (required)
        :type order_id: int
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Order, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = ["order_id"]
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_order_by_id" % _key
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params["order_id"] is not None:
            _path_params["order_id"] = _params["order_id"]

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # authentication setting
        _auth_settings = ["APIKeyHeader"]  # noqa: E501

        _response_types_map = {
            "200": "Order",
            "422": "HTTPValidationError",
        }

        return await self.api_client.call_api(
            "/api/v1/store/order/{order_id}",
            "GET",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    async def get_order_by_id_without_validation(
        self, order_id=None, **kwargs
    ) -> ApiResponse:  # noqa: E501
        """Get Order By Id — without pydantic validation  # noqa: E501

        Like ``get_order_by_id_with_http_info`` but bypasses ``@validate_call``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``get_order_by_id_with_http_info`` are forwarded verbatim.

        :param order_id: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_call on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.get_order_by_id_with_http_info.__wrapped__
        return await _impl(self, order_id, **kwargs)

    @validate_call
    async def place_order(self, order_create: OrderCreate, **kwargs) -> Order:  # noqa: E501
        """Place Order  # noqa: E501

        Place an order for a pet.  Args:     order: Order data from request body.     service: Injected OrderService.  Returns:     The placed order.  # noqa: E501

        :param order_create: (required)
        :type order_create: OrderCreate
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Order
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the place_order_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.place_order_with_http_info(order_create, **kwargs)  # noqa: E501

    @validate_call
    async def place_order_with_http_info(
        self, order_create: OrderCreate, **kwargs
    ) -> ApiResponse:  # noqa: E501
        """Place Order  # noqa: E501

        Place an order for a pet.  Args:     order: Order data from request body.     service: Injected OrderService.  Returns:     The placed order.  # noqa: E501

        :param order_create: (required)
        :type order_create: OrderCreate
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Order, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = ["order_create"]
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method place_order" % _key
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params["order_create"] is not None:
            _body_params = _params["order_create"]

        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get(
            "_content_type",
            self.api_client.select_header_content_type(["application/json"]),
        )
        if _content_types_list:
            _header_params["Content-Type"] = _content_types_list

        # authentication setting
        _auth_settings = ["APIKeyHeader"]  # noqa: E501

        _response_types_map = {
            "200": "Order",
            "422": "HTTPValidationError",
        }

        return await self.api_client.call_api(
            "/api/v1/store/order",
            "POST",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    async def place_order_without_validation(
        self, order_create=None, **kwargs
    ) -> ApiResponse:  # noqa: E501
        """Place Order — without pydantic validation  # noqa: E501

        Like ``place_order_with_http_info`` but bypasses ``@validate_call``
        pydantic validation entirely.  Intended for tests that need to send
        deliberately invalid payloads and assert on the API's error responses.

        All parameters are accepted as-is (no type checking).  The same kwargs
        supported by ``place_order_with_http_info`` are forwarded verbatim.

        :param order_create: (any value accepted — validation is skipped)
        :param _return_http_data_only: when True (default False), return only
                                       the response data rather than an ApiResponse.
        :param _preload_content: if False, raw HTTP body is preserved in
                                 ApiResponse.raw_data.  Default is True.
        :param _request_timeout: timeout for this request.
        :return: Returns the result object.
        :rtype: ApiResponse
        """
        # Retrieve the original undecorated implementation stored by pydantic's
        # @validate_call on the _with_http_info method, then call it
        # directly to skip all pydantic coercion / validation.
        _impl = self.place_order_with_http_info.__wrapped__
        return await _impl(self, order_create, **kwargs)
