name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Release
        uses: softprops/action-gh-release@v3